import 'package:findpro/feature/jobs/add_job/model/job_model.dart';

class MockJobs {
  JobModel cn = JobModel(
      country: 'cn',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1,
      cityId: 6,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel fr = JobModel(
      country: 'fr',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1,
      cityId: 1,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel ind = JobModel(
      country: 'in',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1,
      cityId: 1,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel jp = JobModel(
      country: 'jp',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1000000,
      cityId: 1,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel kr = JobModel(
      country: 'kr',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1,
      cityId: 1,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel ru = JobModel(
      country: 'ru',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1,
      cityId: 1,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel tr = JobModel(
      country: 'tr',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1757,
      cityId: 1,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel us = JobModel(
      country: 'us',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1,
      cityId: 32,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
  JobModel uk = JobModel(
      country: 'uk',
      userId: 50,
      description: 'test test',
      jobCategoryId: 1,
      districtId: 1,
      cityId: 51,
      jobServiceId: 102,
      jobId: 0,
      fullName: 'test kullanıcı',
      createdAt: DateTime.now().toString(),
      hourlyWage: 800,
      mongoDbId: '123');
}
