include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    depend_on_referenced_packages: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    require_trailing_commas: false
    use_build_context_synchronously: false
