name: findpro
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #core
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  logger: ^2.4.0
  #material
  cupertino_icons: ^1.0.6
  lottie: ^2.6.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.2
  #network
  vexana: ^4.0.4
  #state
  flutter_riverpod: ^2.6.1
  auto_route: 7.8.4
  get_it: ^8.0.2
  #permission
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^4.0.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  url_launcher: ^6.3.1
  #notification
flutter_native_splash:
  android_12:
  color: "#024959"
  image: "assets/icon/discovery.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.11
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/icon/
    - assets/lottie/
    - assets/json/


