class CommentFilterService {
  static final List<String> forbiddenWords = [
    'am',
    'amcık',
    'amcik',
    'amcığına',
    'amına',
    'amina',
    'amk',
    'ananı',
    'ananın',
    'ananin',
    'arse',
    'ass',
    'asshole',
    'bastard',
    'bastard',
    'bitch',
    'bitch',
    'bollocks',
    'bugger',
    'bugger',
    'bok',
    'bullshit',
    'cock',
    'crap',
    'cunt',
    'cunt',
    'damn',
    'damn',
    'dick',
    'dick',
    'dickhead',
    'dickhead',
    'dipshit',
    'douche',
    'douchebag',
    'dumbass',
    'fanny',
    'fanny',
    'fuck',
    'fuck',
    'fucker',
    'fucker',
    'fucking',
    'fuckhead',
    'gavat',
    'goğus',
    'got',
    'göğüs',
    'göt',
    'göt',
    'göt deliği',
    'göt kılı',
    'gotten',
    'götten',
    'ibne',
    'ibnelik',
    'jackass',
    'jerkoff',
    'kahpe',
    'meme',
    'memeler',
    'mk',
    'motherfucker',
    'motherfucker',
    'orospu',
    'orospu çocuğu',
    'pezevenk',
    'piç',
    'piss',
    'piss',
    'pissed off',
    'prick',
    'pussy',
    'pussy',
    'schmuck',
    'shit',
    'shit',
    'skank',
    'slut',
    'sik',
    'sikecem',
    'sikeceğim',
    'sikerim',
    'sikicem',
    'sikici',
    'sikicilik',
    'sikilmiş',
    'sikim',
    'sikmek',
    'sikiş',
    'siktir',
    'siktir git',
    'siktir lan',
    'siktir lanet',
    'siktir ol git',
    'son of a bitch',
    'tosspot',
    'twat',
    'twat',
    'twatwaffle',
    'wank',
    'wank',
    'wanker',
    'wanker',
    'wankshaft',
    'wankstain',
    'whore',
    'whore',
    'yarak',
    'yarak kürek',
    'yarak kürekli',
    'yarak kürekleri',
    'yarrak',
    'yarrak kürek',
    'yarrak kürekçi',
    'zilli',
  ];

  static bool containsForbiddenWord(String comment) {
    final words = comment.split(' ');
    return words
        .any((word) => forbiddenWords.contains(word.toLowerCase()));
  }
}
